name: shedule_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  table_calendar: ^3.1.1
  intl: ^0.19.0
  url_launcher: ^6.0.20
  html: ^0.15.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/github_logo.png
    - assets/images/sleeping_man.png


flutter_native_splash:
  color: "#ffffff"
 
  image: assets/images/logo.png
  android_gravity: fill 
  ios_content_mode: scaleAspectFill 
  web_image_mode: center 
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"
